name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'deploy')  # Condition to check commit message
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.18.1
          cache: npm

      - name: Clear Yarn Cache
        run: yarn cache clean

      - name: Install dependencies with retry
        run: |
          retry() {
            for i in {1..5}; do
              "$@" && return 0 || sleep 15;
            done
            return 1
          }
          retry yarn install --frozen-lockfile

      - name: Build website
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }} 
          CHATWOOT_WEBSITE_TOKEN: ${{ secrets.CHATWOOT_WEBSITE_TOKEN }}  # Add this line
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: Lokesh Metta[actions]
          user_email: 26522232+lokeshmetta@users.noreply.github.com